Ancestry.Web/Models/ErrorViewModel.cs
using System;

namespace Ancestry.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Ancestry.Web/Controllers/AdvancedSearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Ancestry.Web.Controllers
{
    public class AdvancedSearchController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Ancestry.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Ancestry.Web.Models;

namespace Ancestry.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Ancestry.Web/Views/AdvancedSearch/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

Ancestry.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.png" alt="ASP.NET" class="img-responsive" style="height: 150px;width:100%"/>
            <div class="carousel-caption" role="option">
                <p>Australia Day 2018</p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.png" alt="Visual Studio" class="img-responsive" style="height:150px;width:100%" />
            <div class="carousel-caption" role="option">
                <p>Australia Day 2018</p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.jpg" alt="Package Management" class="img-responsive"  style="height:150px;width:100%"/>
            <div class="carousel-caption" role="option">
                <p>Australia Day 2018</p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
<div class="row">
    <p></p>
    <h4>Digital Ancestry Basic Search</h4>
    <p></p>
</div>
<div class="row" ng-app="myApp" ng-controller="formCtrl" >
    <form class="form-horizontal" ng-submit="submit()">
        <div class="form-group">
            <div class="col-sm-6">
                <input type="text" class="form-control" ng-model="Name" placeholder="Jane Doe" required="required">
            </div>
            <button type="submit" class="btn btn-primary btn-lg col-sm-6">Search</button>
        </div>
        <div class="form-group">
            <div class="col-sm-6">
                <label class="col-sm-2"> Gender:</label>
                <div class="col-sm-10">
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" ng-model="Male"> Male
                        </label>
                        <label>
                            <input type="checkbox" ng-model="Female"> Female
                        </label>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <a asp-controller="AdvancedSearch" asp-action="Index">Advanced Search</a>
            </div>
        </div>
    </form>
    Results:
    <div class="container-fluid">
        <div class="row table-header-green">
            <div class="col-md-3">ID</div>
            <div class="col-md-3">NAME</div>
            <div class="col-md-3">GENDER</div>
            <div class="col-md-3">BIRTHPLACE</div>
        </div>
        <div class="row" ng-repeat="person in people">
            <div class="col-md-3">{{person.id}}</div>
            <div class="col-md-3">{{person.name}}</div>
            <div class="col-md-3">{{person.gender}}</div>
            <div class="col-md-3">{{person.birthPlace}}</div>
        </div>
    </div>
    <br/>
    <div >
        <!-- pager -->
        <ul ng-if="pager.pages.length" class="pagination">
            @*<li ng-class="{disabled:pager.currentPage === 1}">
                <a ng-click="setPage(1)">First</a>
            </li>*@
            <li ng-class="{disabled:pager.currentPage === 1}">
                <a ng-click="setPage(pager.currentPage - 1)">Previous</a>
            </li>
            <li ng-repeat="page in pager.pages" ng-class="{active:pager.currentPage === page}">
                <a ng-click="setPage(page)">{{page}}</a>
            </li>
            <li ng-class="{disabled:pager.currentPage === pager.totalPages}">
                <a ng-click="setPage(pager.currentPage + 1)">Next</a>
            </li>
            @*<li ng-class="{disabled:pager.currentPage === pager.totalPages}">
                <a ng-click="setPage(pager.totalPages)">Last</a>
            </li>*@
        </ul>
    </div>
</div>

Ancestry.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Digital Ancestry</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">F.A.Amjad</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Digital Ancestry</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.25/angular.min.js"></script>
        @*<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular-route.js"></script>*@
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js"></script>
        @*<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular-route.js"></script>*@
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>